"""
Email sending service with Resend
"""
import os
import requests
from typing import List, Dict


def send_research_report(to_email: str, query: str, report: str, sources: List[Dict]) -> bool:
    """
    Send research report by email
    
    Args:
        to_email: Recipient email
        query: Research query
        report: Generated report
        sources: List of sources used
        
    Returns:
        True if email was sent successfully
    """
    resend_api_key = os.getenv("RESEND_API_KEY")
    
    if not resend_api_key:
        print("RESEND_API_KEY not configured")
        return False
    
    print(f"Sending report to {to_email}...")
    
    # Generate sources HTML
    sources_html = ""
    for i, src in enumerate(sources[:5], 1):
        sources_html += f"""
        <div style="margin-bottom: 15px; padding: 10px; background: #f9f9f9; border-left: 3px solid #008585; border-radius: 4px;">
            <strong style="color: #008585;">[{i}]</strong>
            <a href="{src['url']}" style="color: #333; text-decoration: none; font-weight: 600;">
                {src['title']}
            </a>
            <div style="font-size: 12px; color: #999; margin-top: 5px;">
                Relevance score: {src.get('relevance_score', 'N/A')}
            </div>
        </div>
        """
    
    # Email HTML
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;">
        <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
            
            <!-- Header -->
            <div style="background: #008585; padding: 40px 20px; border-radius: 10px; text-align: center;">
                <h1 style="color: white; margin: 0; font-size: 28px;">Research Report</h1>
                <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0; font-size: 14px;">
                    Generated by DeskResearcher
                </p>
            </div>
            
            <!-- Query -->
            <div style="margin: 30px 0; padding: 20px; background: #f5f7fa; border-radius: 8px;">
                <h2 style="color: #333; margin: 0 0 10px 0; font-size: 18px;">
                    Research Question
                </h2>
                <p style="color: #555; margin: 0; font-size: 16px; line-height: 1.6;">
                    {query}
                </p>
            </div>
            
            <!-- Report -->
            <div style="margin: 30px 0;">
                <h2 style="color: #333; margin: 0 0 15px 0; font-size: 20px;">
                    Executive Report
                </h2>
                <div style="background: white; padding: 25px; border: 1px solid #e0e0e0; border-radius: 8px; line-height: 1.8; color: #444;">
                    {report.replace(chr(10), '<br><br>')}
                </div>
            </div>
            
            <!-- Sources -->
            <div style="margin: 30px 0;">
                <h2 style="color: #333; margin: 0 0 15px 0; font-size: 20px;">
                    Sources Consulted
                </h2>
                {sources_html}
            </div>
            
            <!-- Footer -->
            <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e0e0e0; text-align: center;">
                <p style="color: #999; font-size: 12px; margin: 0;">
                    This report was automatically generated using AI and semantic search with Qdrant
                </p>
                <p style="color: #999; font-size: 12px; margin: 10px 0 0 0;">
                    DeskResearcher &copy; 2024
                </p>
            </div>
            
        </div>
    </body>
    </html>
    """
    
    # Send with Resend API
    try:
        response = requests.post(
            "https://api.resend.com/emails",
            headers={
                "Authorization": f"Bearer {resend_api_key}",
                "Content-Type": "application/json"
            },
            json={
                "from": "DeskResearcher <onboarding@resend.dev>",  # Resend default sender
                "to": [to_email],
                "subject": f"Research Report: {query[:60]}...",
                "html": html_content
            },
            timeout=10
        )
        
        if response.status_code == 200:
            print(f"Email sent successfully to {to_email}")
            return True
        else:
            print(f"Error sending email: {response.status_code} - {response.text}")
            return False
            
    except Exception as e:
        print(f"Exception sending email: {e}")
        return False